name: Lambda CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  FUNCTION_NAME: 'ai-chatbot-${{ github.sha }}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Check IAM Role
        run: |
          aws iam get-role --role-name LambdaExecutionRole > /dev/null || \
          echo "Error: LambdaExecutionRole does not exist"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build Lambda Package
        run: |
          npm run build
          ls dist/lambda/src
          mkdir deploy-package
          cp dist/lambda/src/index.js deploy-package/
          cd deploy-package
          cat index.js
          zip ../lambda-deployment.zip *
      - name: Test Lambda
        run: |
          npm test -- --passWithNoTests
        continue-on-error: false
      - name: Upload to S3
        run: |
          aws s3 cp lambda-deployment.zip s3://${{ secrets.S3_BUCKET_NAME }}/lambda-deployment-${{ github.sha }}.zip
      - name: Substitute template variables
        run: |
          sed -i "s/\${{ secrets.S3_BUCKET_NAME }}/S3_BUCKET_NAME/g" sam-template.yaml
          sed -i "s/lambda-deployment-${{ github.sha }}.zip/S3_OBJECT_KEY/g" sam-template.yaml
      - name: Deploy Using SAM
        run: |
          aws cloudformation deploy \
            --template-file sam-template.yaml \
            --stack-name ai-chatbot-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              FunctionName="ai-chatbot-${{ github.sha }}" \
              S3Bucket="${{ secrets.S3_BUCKET_NAME }}" \
              S3ObjectKey="lambda-deployment-${{ github.sha }}.zip"
         
      - name: Verify Deployment
        run: |
          aws lambda get-function-configuration \
            --function-name "$FUNCTION_NAME"
        continue-on-error: true